dLong=1
dShort=0

MARKET='FTT-PERP'
BASE=10
BASE_DISTANCE=0.01
SAFETY_AMOUNT=20
SAFETY_PERCENT=2
SAFETY_PERCENT_MULTIPLIER=2
SAFETY_AMOUNT_MULTIPLIER=2
SAFETY_ACTIVE_ORDERS=1
SAFETY_NUMBER_ORDERS=10
PROFIT_PERCENT=0.02
DIRECTION=dLong
